{% set name = "luigi" %}
{% set version = "2.7.5" %}
{% set sha256 = "bbfb941254c2f9fe66b14a95d0548958ca848723d29cd4edc928e5341c042646" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/spotify/{{ name }}/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - luigi = luigi.cmdline:luigi_run
    - luigid = luigi.cmdline:luigid
    - luigi-grep = luigi.tools.luigi_grep:main
    - luigi-deps = luigi.tools.deps:main
    - luigi-deps-tree = luigi.tools.deps_tree:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - pyparsing
    - tornado >=4.0,<6
    - python-daemon <3.0  # [not win]

test:
  imports:
    - luigi
    - luigi.contrib
    - luigi.contrib.hdfs
    - luigi.tools
    - luigi.scheduler
  commands:
    - luigi --help
    - luigid --help
    - luigi-grep --help
    - luigi-deps --help
    - luigi-deps-tree --help

about:
  home: https://github.com/spotify/luigi
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: 'Workflow mgmgt + task scheduling + dependency resolution.'
  description: |
    Luigi handles dependency resolution, workflow management, visualization,
    handling failures, command line integration, and much more. It also comes
    with Hadoop support built in.
  dev_url: https://github.com/spotify/luigi
  doc_url: https://luigi.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
    - nehaljwani
