{% set name = "luigi" %}
{% set version = "3.7.2" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/spotify/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 8e6610e69befa0d39caa11c069e26c70f1cd2715b3b142f012a608652c404be5

build:
  number: 1
  skip: true  # [py<38 or py>312]
  script: {{ PYTHON }} -m pip install . --no-deps -vv --no-build-isolation
  entry_points:
    - luigi = luigi.cmdline:luigi_run
    - luigid = luigi.cmdline:luigid
    - luigi-grep = luigi.tools.luigi_grep:main
    - luigi-deps = luigi.tools.deps:main
    - luigi-deps-tree = luigi.tools.deps_tree:main

requirements:
  host:
    - python
    - pip
    - hatchling
    - hatch-fancy-pypi-readme
  run:
    - python
    - python-dateutil >=2.7.5,<3
    - tenacity >=8,<9
    - tornado >=5.0,<7
    - python-daemon  # [not win]
    - typing-extensions >=4.12.2
  run_constrained:
    - prometheus_client >=0.5,<0.15
    - toml <2.0.0

test:
  source_files:
    - test
  imports:
    - luigi
    - luigi.configuration
    - luigi.contrib
    - luigi.contrib.hdfs
    - luigi.tools
    - luigi.scheduler
  requires:
    - pip
    - pytest
  commands:
    - luigi --help
    - luigid --help
    - luigi-grep --help
    - luigi-deps --help
    - luigi-deps-tree --help
    # Skip pip because python-daemon is not available on win.
    - pip check  # [not win]
    # Run only basic tests since tests demands specific dependencies versions which are not available
    - pytest -v test/most_common_test.py test/import_test.py

about:
  home: https://github.com/spotify/luigi
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: Workflow mgmgt + task scheduling + dependency resolution.
  description: |
    Luigi handles dependency resolution, workflow management, visualization,
    handling failures, command line integration, and much more. It also comes
    with Hadoop support built in.
  dev_url: https://github.com/spotify/luigi
  doc_url: https://luigi.readthedocs.io

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
    - nehaljwani
