{% set version = "2.8.3" %}

package:
  name: luigi
  version: {{ version }}

source:
  url: https://github.com/spotify/luigi/archive/{{ version }}.tar.gz
  sha256: 5997ac3f77f7a6ebbe275d15166b8501b2c1d72ddfbbb2b91479a9dee03118c4

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - luigi = luigi.cmdline:luigi_run
    - luigid = luigi.cmdline:luigid
    - luigi-grep = luigi.tools.luigi_grep:main
    - luigi-deps = luigi.tools.deps:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - tornado >=4.0,<5
    - python-daemon <2.2.0  # [not win]
    - python-dateutil==2.7.5
    - enum34  # [py<34]

test:
  imports:
    - luigi
    - luigi.contrib
    - luigi.contrib.hdfs
    - luigi.tools
    - luigi.scheduler
  commands:
    - luigi --help
    - luigid --help
    - luigi-grep --help
    - luigi-deps --help

about:
  home: https://github.com/spotify/luigi
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: 'Workflow mgmgt + task scheduling + dependency resolution.'
  dev_url: https://github.com/spotify/luigi
  doc_url: https://luigi.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
