{% set version = "2.8.12" %}

package:
  name: luigi
  version: {{ version }}

source:
  url: https://github.com/spotify/luigi/archive/{{ version }}.tar.gz
  sha256: 02d7af97d5254bc7f04f1070f3ac2e8bba559ca11e73f252a37bef3d2fbd1483

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"
  entry_points:
    - luigi = luigi.cmdline:luigi_run
    - luigid = luigi.cmdline:luigid
    - luigi-grep = luigi.tools.luigi_grep:main
    - luigi-deps = luigi.tools.deps:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - tornado >=4.0,<6
    - python-daemon <2.2.0  # [win]
    - python-daemon  # [not win]
    - python-dateutil >=2.7.5,<3
    - enum34 >1.1.0  # [py<34]
    - prometheus_client ==0.5.0
    - toml <2.0.0

test:
  requires:
    - pip
  imports:
    - luigi
    - luigi.contrib
    - luigi.contrib.hdfs
    - luigi.tools
    - luigi.scheduler
  commands:
    - luigi --help
    - luigid --help
    - luigi-grep --help
    - luigi-deps --help
    - pip check  # [not win]

about:
  home: https://github.com/spotify/luigi
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: 'Workflow mgmgt + task scheduling + dependency resolution.'
  dev_url: https://github.com/spotify/luigi
  doc_url: https://luigi.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
