{% set version = "2.7.8" %}

package:
  name: luigi
  version: {{ version }}

source:
  url: https://github.com/spotify/luigi/archive/{{ version }}.tar.gz
  sha256: d0117738c83824f12ddd3dfe5b62ab6fec2de22c1f517fbe3a51689bbd5d0a35

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - luigi = luigi.cmdline:luigi_run
    - luigid = luigi.cmdline:luigid
    - luigi-grep = luigi.tools.luigi_grep:main
    - luigi-deps = luigi.tools.deps:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - setuptools
    - tornado >=4.0,<5
    - python-daemon <3.0  # [not win]
    - enum34  # [py<34]
    - botocore

test:
  imports:
    - luigi
    - luigi.contrib
    - luigi.contrib.hdfs
    - luigi.tools
    - luigi.scheduler
  commands:
    - luigi --help
    - luigid --help
    - luigi-grep --help
    - luigi-deps --help

about:
  home: https://github.com/spotify/luigi
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: 'Workflow mgmgt + task scheduling + dependency resolution.'
  dev_url: https://github.com/spotify/luigi
  doc_url: https://luigi.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
