{% set version = "2.7.9" %}

package:
  name: luigi
  version: {{ version }}

source:
  url: https://github.com/spotify/luigi/archive/{{ version }}.tar.gz
  sha256: 078d94cb5771505c493ce4f53c2079ba8c4f71c9083bd76d046e51431ec55695

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  entry_points:
    - luigi = luigi.cmdline:luigi_run
    - luigid = luigi.cmdline:luigid
    - luigi-grep = luigi.tools.luigi_grep:main
    - luigi-deps = luigi.tools.deps:main
    - luigi-deps-tree = luigi.tools.deps_tree:main

requirements:
  host:
    - python
    - pip
  run:
    - python
    - setuptools
    - tornado >=4.0,<5
    - python-daemon <3.0  # [not win]
    - enum34  # [py<34]
    - botocore

test:
  imports:
    - luigi
    - luigi.contrib
    - luigi.contrib.hdfs
    - luigi.tools
    - luigi.scheduler
  commands:
    - luigi --help
    - luigid --help
    - luigi-grep --help
    - luigi-deps --help
    - luigi-deps-tree --help

about:
  home: https://github.com/spotify/luigi
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: 'Workflow mgmgt + task scheduling + dependency resolution.'
  description: |
    Luigi handles dependency resolution, workflow management, visualization,
    handling failures, command line integration, and much more. It also comes
    with Hadoop support built in.
  dev_url: https://github.com/spotify/luigi
  doc_url: https://luigi.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - ocefpaf
    - kwilcox
    - nehaljwani
