travis:
  secure:
    BINSTAR_TOKEN: CooZ66SonieLxio1+x/XN1MybLFB1c7fi2bMMzHGnCox1owb0x3Hz6XdDbVRUXfZEoQvO9eD/wfQ89SLBe0GRDXgyMjaJfZc6fzJycioiRpsUWC3Rl8+nI5XuvCZ0vWglmuz0uQtt52806uP8o/q2DhRzR3gylikBICL3ipR6atkHmmKmYoYoJQ2+e6NgmeGkZY8vmXMrFX9lM6I6Y3aqoYXOk6TsVzdxHmwSd/oo0DBMV1UM8pHBM476CRJuEXCYtAeoPjtcZQWeZyNkzaOJrF2qqtTsah/AH4qJ585uogHMuvr79HYp3sDS046uiSxmneGxYie7ZboYlQG2QUs9GvPzFHd2hOByGT7V4KNcPT4MPVsWFQ6D2eeGrRtOawV2lZiwrNjZDprGfLDrfX4DHK0CBA5vk2fWeOWIfCVLGRNsJeEkE2BjlNCd/rR6c6YUiCjVlwM9WFzbImJP5oJ0AJxUlAL9VukvhpxQ9CUKF2oMgxS0eIGawBvZewSDF8luez+Q5HRJrK9lKt1fcEDkGI5k5QMD1l1uhjSmsliGWEgLbZXggU0r20AsYY0Saq9QUn0klYwQd9SgVDTGtH0CuX52qletyeSPjL6xgpbtAVzRN6ZFtJH+GiuISCYriHCe0Pxt5pOWKLydVxdQ3NuMuPn97qwgvqJx2C85u6xSGU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
