travis:
  secure:
    BINSTAR_TOKEN: RC2fqKtrkixHpVQ3fNTqhXr5zkC3xHJyEDAfnGo5xf6Y9gvBcU2ajfNrriHjnGEJVVVZCgfNUG/bXEjDTo2ZEs97OjXkUSp8DbMyaAoK5qcuNG0xmnTQqVxCSCWhxKuW++ZPizTSUaEDRmT9ReEXV3G7AZo4uKxUdRzQimtecUetHPV1vATR8pNLyubwwlyHWlxiyGC4kgEJh3/8HMzBeBTLeqiTZ/dtKw6a74CcxD1/V9Cy52BWTxTTPk279fZU6FRNtxADs4Ki1dMsyzy2+CNCz1KuUuJqtVFKMOfilDCsvCb+PFTKBIDF42rKAVQbzhgzWsju4Cp9p9LlrmAr961x+p6OgljrzfgUAw4VI8PEt6JH0aFS/JNU6uen8n4+DKF5+pmVHW/g5bEC2CwzwJCHfrjLNZ0TgLOtqun6g/0Yn8XtxK8/XyDsU8e74h+8bBj+rDayqzl4YfRVOjq5rD9zJm7TzCpKNQXlQp1WY6TcqYOIdEEDnEoApJBLlmVAMv/GCHscjH7zMtKw+UPn5fL+4da3lQcY7xYRgK3Xq2h5JSsyscbT8ctv8UuHYS4ovJ8VVHqJIGCy6DtUh4YBu6h6C1tWVav1SRPhQRU6PrbONTiYnCV6QE7TUp3mEO8BIoUeny5EHIlP0UyWdgDpFreg0A8X8uf823GxlkI2oIc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
