travis:
  secure:
    BINSTAR_TOKEN: HK2QWj0sr2o0HlaG76g4MI+iDTsx++q1gO91B5KS8qujRK0JXyL1pRi1nve1NN2PUjpa8rqcjbMFgjex9ZFSVVWHDAxncFb8fiVyAJbZTKLcsR0/o4IZi/UHjCZv+4paolMKRa2zNVk53BpUfMSuvzh4JP2dXAZqeUsHw+9ZKHiCK1Ygi27KG3m3gP/SGPFZDDIkM1xTA+b6EuuEsE1c1ro4HVJ7Q661ZcNXr2EuWRCzhFnWTzRu7efTrLFh1su922MeiAeCOVOHQbjE4cKAraKEoFKtoRgO6hKVECjV4gPiAoaTaHp3N9Ca/yTUNe3lb1l/b628xHb2933z3YV2npK8Ron1JdQDRiAsxx5D8ykI2VzEYrdLtSUp6ziJJXJU+tDyhk/0vqfBje0tmYvmiUzqahycWT8y5AkqVFYZII0NKG4V2f4VtGL2XDjY82wAl21cbBhnHsdfIK1e8LP4FiJBBFRWe1TkhJj4C46S0J1DNgZBZ1R3r6tm8gMl4enidLQIF1X6Jm8OxJLECqFxRJdYjZKtZheBrmGEo0X62WjG2HChItIySL6JvQNuvDgwgSiUkw/QgpI0xRjDhYOgFbT8kpA/Epml43vJBqB5VJHF1aXO9wVUSlEnlUgUrbcDoYQ5wDG/33bLw0unAqZLxqgs9UyIlG5nTciL2AOeA0k=
appveyor:
  secure:
    BINSTAR_TOKEN: !!binary |
      TVA0aFpZeWxEeVVXRXNydDN1M2NvZDJzYkZlUndVemlIMDJtdlFPZGJqc1RPL2wxeUl4RGtQLzc2
      clNJamNHQw==
